### PR TITLE
Fix whitespaces and special characters in Rule Names

### LINKED ISSUE #21: Special characters in rule names not handled
A rule name with a space or other special character will fail when it gets interpreted by SQL. The rule-name string should either be cleansed or should throw an error if it's not within acceptable formats.

### PR DESCRIPTION
**Pull request by goodwillpunning**
This commit fixes #21. Previously, white spaces and special characters would cause a runtime exception when failed column (rule names) were selected to build the failure report. This commit properly escapes white spaces and special characters using the backtick \`  syntax.

### CODE REVIEW

**Review by GeekSheikh — CHANGES_REQUESTED** [review]
While I think this works for the purpose of displaying the a rule name with special chars I'm concerned that the rule name throughout the evaluated rules may cause an issue and furthermore that the final output rule name won't match the rule names that are evaluated. I think the rule name should be changed at the instantiation of a rule AND throw a warning letting the user know that the rule name was changed due to special characters. 

I think we could change ruleName in Rule.scala to a private val, call it `_ruleName` and then create a function called `ruleName` that retreives the ruleName while fixing the special chars. 

What are your thoughts?

**Comment by goodwillpunning** [comment]
I think that's a great idea.

File: src/main/scala/com/databricks/labs/validation/Rule.scala [hunk 1]
```diff
@@ -95,11 +94,11 @@ class Rule(
...
-  def cleanseRuleName(ruleName: String): String = {
-    if (ruleName.contains(" ")) logger.warn("Replacing whitespaces in Rule Name with underscores.")
-    val removedWhitespaceRuleName = ruleName.trim.replaceAll(" ", "_")
+  def ruleName: String = {
+    if (_ruleName.contains(" ")) logger.warn("Replacing whitespaces in Rule Name with underscores.")
+    val removedWhitespaceRuleName = _ruleName.trim.replaceAll(" ", "_")
     val specialCharsPattern = "[^a-zA-z0-9_-]+".r
-    if (specialCharsPattern.findAllIn(ruleName).toSeq.nonEmpty) logger.warn("Removing special characters from Rule Name.")
+    if (specialCharsPattern.findAllIn(_ruleName).toSeq.nonEmpty) logger.warn("Removing special characters from Rule Name.")
     removedWhitespaceRuleName.replaceAll("[^a-zA-Z0-9_-]", "")
```
Comment (GeekSheikh) [inline src/main/scala/com/databricks/labs/validation/Rule.scala:102]: I think we should allow underscores and dashes as those don't conflict with SQL (that I know of). Additionally, rather than just dropping the characters, I think we should replace the special chars with `_`. This lets the user know that it was stripped as well and where it was stripped from. You good with that?

Comment (GeekSheikh) [inline src/main/scala/com/databricks/labs/validation/Rule.scala:102]: I think we should allow underscores and dashes as those don't conflict with SQL (that I know of). Additionally, rather than just dropping the characters, I think we should replace the special chars with `_`. This lets the user know that it was stripped as well and where it was stripped from. You good with that?

**Review by GeekSheikh — CHANGES_REQUESTED** [review]
Did you get the name cleansed for the groupBys as you noted in slack? I don't see the change here, wondering if I missed it or you put it in a diff PR.

Requesting one simple change but looks great overall!

File: src/main/scala/com/databricks/labs/validation/Rule.scala (hunk 1 above)
Comment (goodwillpunning) [reply src/main/scala/com/databricks/labs/validation/Rule.scala:102]: Sure, that works!

**Review by GeekSheikh — APPROVED** [review]
LGTM
